cockroachdb: fix table scattering in multi-register
Fixes https://github.com/cockroachdb/cockroach/issues/37470.
Fixes https://github.com/cockroachdb/cockroach/issues/37471.
Fixes https://github.com/cockroachdb/cockroach/issues/37472.
Fixes https://github.com/cockroachdb/cockroach/issues/37473.
Fixes https://github.com/cockroachdb/cockroach/issues/37474.
Fixes https://github.com/cockroachdb/cockroach/issues/37475.

This was failing with the following error:
```
org.postgresql.util.PSQLException: A result was returned when none was expected.
```

Using `c/query` instead of `c/execute!` fixes this (this time I confirmed).